project:
  type: book
  output-dir: docs

book:
  title: "mapa tutorial"
  date: "6/8/2025"
  favicon: "/images/mapa_logo.png"
  description: Functional Module Annotation for Pathway Analysis Results Using LLM
  url: http://www.shen-lab.org/mapa-tutorial/
  sidebar:
    logo: "images/mapa_logo.png"
    search: true
  repo-url: https://github.com/jaspershen-lab/mapa-tutorial
  repo-actions: [edit, issue, source]
  image: "images/mapa_logo.png"
  
  chapters:
    - index.qmd
    
    - part: "mapa R Package"
      chapters:
        - 01_package_installation.qmd
        - 02_input.qmd
        - 03_enrichment_analysis.qmd
        - 04_sim_cluster.qmd
        - 04_embed_cluster.qmd
        - 05_llm_interpretation.qmd
        - 06_data_vis.qmd
        - 07_res_report.qmd
    
    - part: "mapa Shiny App"
      chapters:
        - 01_shinyapp_installation.qmd
        - 02_input_shiny.qmd
        - 03_enrichment_analysis_shiny.qmd
        - 04_sim_cluster_shiny.qmd
        - 04_embed_cluster_shiny.qmd
        - 05_llm_interpretation_shiny.qmd
        - 06_data_vis_shiny.qmd
        - 07_res_report_shiny.qmd

    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    css: custom.css

editor: visual

